//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestiondeStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int Id_Commande { get; set; }
        public Nullable<int> Id_Produit { get; set; }
        public int Id_Modele { get; set; }
        public int Prix_Achat { get; set; }
        public int Quantite_Cmd { get; set; }
        public int Montant_Cmd { get; set; }
        public System.DateTime Date_Cmd { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
